---
- name: Configurar ambiente de desenvolvimento Fedora
  hosts: localhost
  connection: local
  become: true

  vars:
    nodejs_version: '20'

  pre_tasks:
    - name: Atualizar pacotes
      ansible.builtin.dnf:
        name: "*"
        state: present

  tasks:
    - name: Instalar pacotes base
      ansible.builtin.dnf:
        name:
          - git
          - php
          - docker
          - docker-compose
          - flatpak
        state: present

    - name: Importar chave GPG do VS Code
      ansible.builtin.rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc

    - name: Adicionar repositório do VS Code
      ansible.builtin.yum_repository:
        name: code
        description: Visual Studio Code
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        enabled: true
        gpgcheck: true
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc

    - name: Instalar VS Code
      ansible.builtin.dnf:
        name: code
        state: present

    - name: Habilitar módulo Node.js {{ nodejs_version }}
      ansible.builtin.command:
        cmd: dnf module enable -y nodejs:{{ nodejs_version }}
      args:
        creates: "/usr/lib/node_modules"

    - name: Instalar Node.js
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: Instalar pacotes npm globais
      community.general.npm:
        name: "{{ item }}"
        global: true
      loop:
        - pnpm
        - yarn
        - '@nestjs/cli'

    - name: Baixar instalador do Composer
      ansible.builtin.get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-setup.php
        mode: '0644'

    - name: Instalar Composer globalmente
      ansible.builtin.command:
        cmd: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
      args:
        creates: /usr/local/bin/composer

    - name: Instalar Laravel Installer via Composer
      community.general.composer:
        command: require
        arguments: laravel/installer
        global_command: true
        executable: /usr/local/bin/composer

    - name: Adicionar Composer bin ao PATH
      ansible.builtin.lineinfile:
        path: "/home/{{ ansible_user_id }}/.bashrc"
        line: 'export PATH="$PATH:$HOME/.config/composer/vendor/bin"'
        state: present
      become: false

    - name: Iniciar e habilitar Docker
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started

    - name: Adicionar usuário ao grupo docker
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: true

    - name: Adicionar repositório Flathub
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        method: system

    - name: Instalar LibreWolf via Flatpak
      community.general.flatpak:
        name: io.gitlab.librewolf-community
        state: present

    - name: Adicionar repositório GitHub CLI
      ansible.builtin.yum_repository:
        name: github-cli
        description: GitHub CLI
        baseurl: https://cli.github.com/packages/rpm
        enabled: true
        gpgcheck: true
        gpgkey: https://cli.github.com/packages/rpm/gh-cli.repo.gpg

    - name: Instalar GitHub CLI
      ansible.builtin.dnf:
        name: gh
        state: present
